image: docker:latest


stages:
  - build
  - deploy

build:
  type: build
  stage: build
  script:
     - "docker info"
     - "docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY"
     - "docker build -t $CI_REGISTRY_IMAGE/meteor:latest ."
     - "docker push $CI_REGISTRY_IMAGE/meteor"

deploy:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  script:
    - upgrade --environment dev --stack portal --service portal
