image: docker:latest

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  type: build
  stage: build
  script:
     - "docker build -t $CI_REGISTRY_IMAGE/meteor:latest ."
     - "docker push $CI_REGISTRY_IMAGE/meteor"
